focal_populations: ['FOC0', 'FOC1']
focal_population_sizes: [5, 10]
reference_populations: ['REF0', 'REF1']
reference_population_sizes: [2, 2]
demography: utilities/example_demography.yaml
output_directory: ./example_data/
